name: Build Conan Caches

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'scripts/getBuildConanCachesPackageInfo.py'
      - '.github/workflows/build_conan_caches.yml'
      - 'conan.lock'
      - 'modules/conan-center-index'

  pull_request:
    paths:
      - 'scripts/getBuildConanCachesPackageInfo.py'
      - '.github/workflows/build_conan_caches.yml'
      - 'conan.lock'
      - 'modules/conan-center-index'

  schedule:
    - cron:  '11 6 * * *'

jobs:
  get_packages_to_build:

    name: Get Packages to Build
    runs-on: ubuntu-latest

    outputs:
      package_info: ${{ steps.gen_package_info.outputs.package_info }}
      merge_info: ${{ steps.gen_package_info.outputs.merge_info }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Setup Conan environment
        uses: ./.github/workflows/conan_setup_action

      - name: Generating Package Info
        id: gen_package_info
        run: |
          python scripts/getBuildConanCachesPackageInfo.py cairo cpython qt ffmpeg >> $GITHUB_OUTPUT

  build_package_matrix:
    strategy:
      fail-fast: false
      matrix:
        packages: ${{ fromJson(needs.get_packages_to_build.outputs.package_info) }}

    name: Build ${{ matrix.packages.conan_profile }} - ${{ matrix.packages.name }}
    runs-on: ${{ matrix.packages.runs_on }}
    continue-on-error: true
    needs: [get_packages_to_build]

    env:
      CONAN_HOME: ${{ matrix.packages.runs_on == 'windows-latest' && format('D:\cbw', github.workspace) || '~/.conan2'}}
      CONAN_CACHE_FILENAME: conan_cache_save-${{ matrix.packages.name }}-${{ matrix.packages.conan_profile }}.tgz

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Setup Conan environment
        uses: ./.github/workflows/conan_setup_action
        with:
          conan_profile: ${{ matrix.packages.conan_profile }}

      - name: Build package
        run: |
          conan install -pr:a ${{ matrix.packages.conan_profile }} ${{ matrix.packages.build_args  }} --build=missing

      - name: Remove unnecessary files from cache
        run: |
          conan cache clean '*'

      - name: Remove clang so it doesn't get saved in the cache file.
        run: |
          conan remove -c 'clang/*'

      - name: Remove msys2 package from cache
        if: runner.os == 'Windows'
        run: |
          conan remove -c "msys2/*"

      - name: Save cache to file
        run: |
          conan cache save --file=${{ env.CONAN_CACHE_FILENAME }} '*:*'

      - name: Upload cache
        uses: actions/upload-artifact@v4.3.1
        with:
          name:  ${{ env.CONAN_CACHE_FILENAME }}
          path:  ${{ env.CONAN_CACHE_FILENAME }}

  merge_packages_matrix:
    strategy:
      fail-fast: false
      matrix:
        merge_info: ${{ fromJson(needs.get_packages_to_build.outputs.merge_info) }}

    name: Merge ${{ matrix.merge_info.conan_profile }} packages
    runs-on: ${{ matrix.merge_info.runs_on }}
    needs: [get_packages_to_build, build_package_matrix]

    env:
      CONAN_HOME: ${{ matrix.merge_info.runs_on == 'windows-latest' && format('D:\cbw', github.workspace) || '~/.conan2'}}
      CONAN_CACHE_FILENAME: conan_cache_save-${{ matrix.merge_info.conan_profile }}.tgz

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Setup Conan environment
        uses: ./.github/workflows/conan_setup_action
        with:
          conan_profile: ${{ matrix.merge_info.conan_profile }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: conan_cache_save-*-${{ matrix.merge_info.conan_profile }}.tgz
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Add each package to cache
        run: |
          python3 scripts/restoreConanCacheSaves.py --remove artifacts

      - name: Remove unnecessary files from cache
        run: |
          conan cache clean '*'

      - name: Build openfx-io dependencies
        run: |
          conan install -pr:a ${{ matrix.merge_info.conan_profile }} --requires 'openfx-io/master' --update 'openfx-io/master' --build missing --lockfile-partial

      - name: Remove unnecessary files from cache
        run: |
          conan cache clean '*'

      - name: Remove openfx-io so it doesn't get saved in the cache file.
        run: |
          conan remove -c 'openfx-io/*'

      - name: Build Natron
        run: |
          conan install -pr:a ${{ matrix.merge_info.conan_profile }} --requires 'natron/conan_build' --update 'natron/conan_build' --build missing --lockfile-partial

      - name: Remove unnecessary files from cache
        run: |
          conan cache clean '*'

      - name: Remove Natron so it doesn't get saved in the cache file.
        run: |
          conan remove -c 'natron/*'

      - name: Remove clang so it doesn't get saved in the cache file.
        run: |
          conan remove -c 'clang/*'

      - name: Remove msys2 package from cache
        if: runner.os == 'Windows'
        run: |
          conan remove -c "msys2/*"

      - name: Save cache to file
        run: |
          conan cache save --file=${{ env.CONAN_CACHE_FILENAME }} '*:*'

      - name: Upload cache
        uses: actions/upload-artifact@v4.3.1
        with:
          name:  ${{ env.CONAN_CACHE_FILENAME }}
          path:  ${{ env.CONAN_CACHE_FILENAME }}
